name: (Prod) Create Release Tag & Deploy

on:
  push:
    branches:
      - 'master'

permissions:
  actions: write
  contents: write
  pull-requests: read
  id-token: 'write'

jobs:
  build:
    name: '🚀 Release'
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'revert') &&
      !contains(github.event.head_commit.message, 'hotfix')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # registry-url: https://registry.npmjs.org
          # cache: pnpm
     