name: Validate Release Branch

on:
  push:
    branches:
      - 'sit'
      - 'main'

permissions:
  actions: write
  contents: write
  pull-requests: read
  id-token: 'write'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm manually
        run: |
          npm install -g pnpm
          echo "pnpm version: $(pnpm --version)"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # registry-url: https://registry.npmjs.org
          # cache: pnpm