# Cherry pick comment
name: Run on PR merge to sit (Staging Build)

on:
  pull_request:
    types: [closed]
    branches:
      - sit
    paths-ignore:
      - '**/*.md'

permissions:
  actions: write
  contents: write

jobs:
  run_on_merge:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # registry-url: https://registry.npmjs.org
          # cache: pnpm